export enum MovieGender {
  Surreal = 'Surreal',
  Action = 'Action',
  Adventure = 'Adventure',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Drama = 'Drama',
  Fantasy = 'Fantasy',
  Historical = 'Historical',
  HistoricalFiction = 'HistoricalFiction',
  Horror = 'Horror',
  MagicalRrealism = 'MagicalRrealism',
  Mystery = 'Mystery',
  ParanoidFiction = 'ParanoidFiction',
  Philosophical = 'Philosophical',
  Political = 'Political',
  Romance = 'Romance',
  Saga = 'Saga',
  Satire = 'Satire',
  ScienceFiction = 'ScienceFiction',
  Social = 'Social',
  Speculative = 'Speculative',
  Thriller = 'Thriller',
  Urban = 'Urban',
  Western = 'Western',
}
